services:
  - type: web
    name: blueprint-test
    runtime: static
    repo: https://github.com/kitemongerer/blueprints-test.git # optional
    branch: main # optional (defaults to master)
    buildCommand: "true"
    staticPublishPath: "./"
    headers:
    - path: /*
      name: X-Frame-Options
      value: sameorigin
    - path: /*
      name: something-else
      value: sameorigin
    routes:
    - type: redirect
      source: /old
      destination: /new
    - type: rewrite
      source: /b/*
      destination: /a
